### ISSUE TITLE
Add Exponential Search

### ISSUE THREAD

**Issue by TarunISCO** [ashu-beckham/Algo#25]
https://www.geeksforgeeks.org/exponential-search/ 
Want to work on this issue: Yes
Language: JAVA

**Comment by ashu-beckham** [comment]
@TarunISCO  Iam not able to understand Exponential search.

**Comment by TarunISCO** [comment]
@ashu-beckham this is new to me also. I'll read about it.

**Comment by ashu-beckham** [comment]
Ok . Then teach me 👍
