### ISSUE TITLE
Add Shortest Path Algorithms

### ISSUE THREAD

**Issue by ashu-beckham** [ashu-beckham/Algo#30]
[Shortest Path Algorithm](https://www.geeksforgeeks.org/greedy-algorithms-set-6-dijkstras-shortest-path-algorithm/) 
Want to work on this issue : Yes
Language :JAVA

**Comment by ashu-beckham** [comment]
@TarunISCO Its weekend time , you should complete some issues.

**Comment by TarunISCO** [comment]
@ashu-beckham yeah bro. I'll try.

**Comment by ashu-beckham** [comment]
👍

**Comment by TarunISCO** [comment]
@ashu-beckham  I think issue title is not appropriate.

**Comment by TarunISCO** [comment]
I think it is for Dijsktra's Algorithm.

**Comment by ashu-beckham** [comment]
@TarunISCO No , it was right . There are more than one shortest path algorithms . We can make a folder of shortest path algorithm inside graph algorithms and add each of them . 
You can refer here [Shortest path algorithms](https://www.google.co.in/search?source=hp&ei=WThbWqGfBIL28gWIqpjYCQ&q=shortest+path+algorithms&oq=shortest+path+algorithms&gs_l=psy-ab.3..0l7.938.7669.0.7959.13.11.0.1.1.0.283.1714.0j2j5.7.0....0...1c.1.64.psy-ab..5.8.1718.0..0i131k1.0.THv7tBy8hkA)

**Comment by TarunISCO** [comment]
it will be better to create a new issue for each algorithm

**Comment by ashu-beckham** [comment]
@TarunISCO Sure , we can do it that way.
