### ISSUE TITLE
Add Quick Sort

### ISSUE THREAD

**Issue by TarunISCO** [ashu-beckham/Algo#9]
[Quick Sort](https://www.geeksforgeeks.org/quick-sort/)
Want to work on this issue: Yes

**Comment by TarunISCO** [comment]
I'm working on this.

**Comment by ashu-beckham** [comment]
ok

**Comment by ashu-beckham** [comment]
@TarunISCO please complete the work ASAP.

**Comment by TarunISCO** [comment]
yeah, I'm working on it.
